---
baseURL: gaussej.com.br
languageCode: en-us
title: Gauss Ej | Empresa Júnior de Estatística
summaryLength: 10
enableRobotsTXT: true
googleAnalytics: ''
enableGitInfo: true
pygmentsCodeFences: false
defaultContentLanguageInSubdir: true
DefaultContentLanguage: en
params:
  cookies:
    enable: true
    expire_days: 2
  logo: images/logo.svg
Params:
  listeLangues:
  - author: Gauss
    code: en
    description: Transformando dados em Insights
Languages:
  en:
    dateFormat: 2/10/2006
    home: Home
    languageCode: en-us
    logo: images/logo.svg
    menufixed: true
    params:
      contact:
        address: Bloco 910 Campus do Pici, Dema ,UFC  <br> Pici , Fortaleza-CE
        enable: true
        dribbble: 
        facebook: https://www.facebook.com/GaussUFC
        fax: 
        instagram: https://www.instagram.com/gauss.ufc/
        linkedin: https://www.linkedin.com/company/gauss-ufc/
        twitter: 
        mapLatitude: "-3.7449987672084397"
        mapLongitude: "-38.57411386931414"
        mapMarker: images/marker.png
        phone: "(85) 98176-7985"
        subtitle: Mande seu email com sua dúvida, adoraremos responde-la.
        title: Entre em Contato.
        topTitle: Marque sua consutoria conosco!
      cta:
        bg: images/call-to-action/call-to-action-bg-2.jpg
        btnText: Entre em Contato
        enable: true
        subtitle: Fazemos reuniões presencias e onlines.
        title: Marque sua reunião de diagnóstico.
      hero:
        btnText: Saiba Mais
        btnURL: 
        button: false
        description: Somos uma empresa júnior especializada em análise estatística
          em diferentes áreas.
        enable: true
        heading: Transformandos dados em Insight.
        videoThumb: 
        videoURL: 
      title: Gauss Ej
    weight: 2
menu:
  nav:
  - url: contact
    name: contact
    weight: 3
  - url: service
    name: service
    weight: 2
  - url: about
    name: about
    weight: 1
